#!/usr/bin/env bash

### Copy this into .git/hooks and overwrite the empty one.
### This will ensure the bundle and ins-outs verification checks won't fail for you.

echo "----- Pre-commit -----"
set -ex
npm run bundle
npm run generate-ins-outs
git add -v dist/ src/generated
