name: 'OpenShift Login'
description: 'Log into an OpenShift cluster and set up a Kubernetes context'
author: 'Red Hat'
branding:
  icon: circle
  color: red
inputs:
  ##### Inputs for login
  openshift_server_url:
    description: 'Openshift Server URL.'
    required: true
  ### Authenticating
  openshift_token:
    description: 'Openshift Bearer Token. Store in a secret.'
    required: false
  openshift_username:
    description: 'Openshift Username. Must be used with openshift_password.'
    required: false
  openshift_password:
    description: 'Openshift Password. Store in a secret. Must be used with openshift_username.'
    required: false
  ### TLS Cert options
  insecure_skip_tls_verify:
    description: 'Skip TLS certificate verification when connecting to the cluster.'
    required: false
    default: 'false'
  certificate_authority_data:
    description: "Contents of a Certificate Authority (.crt) file for your cluster's SSL certificate. Store in a secret."
    required: false
  ##### Inputs for kubeconfig
  namespace:
    description: "Set current context's namespace to this, after logging in."
    required: false
  ##### Other inputs
  reveal_cluster_name:
    description: "By default, the cluster name is masked, since it can be used to derive the server URL. Set this to true to skip masking the cluster name."
    required: false
    default: "false"


runs:
  using: 'node12'
  main: 'dist/index.js'
