name: OpenShift tests!

# Run this workflow every time a new commit pushed to your repository
on: [ push, workflow_dispatch ]

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  auth:
    name: OpenShift Auth
    # Set the type of machine to run on
    runs-on: ubuntu-18.04
    outputs:
      kubeconfig: ${{steps.auth.outputs.kubeconfig}}

    steps:
      - name: checkout
        uses: actions/checkout@v2
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #- name: Init OpenShift
        #uses: redhat-developer/openshift-actions@v2.1.0

      - name: auth
        id: auth
        shell: bash
        run: |
          oc login --token=${{ secrets.API_TOKEN }} --server=${{ secrets.OPENSHIFT_SERVER_URL }} --insecure-skip-tls-verify=true
          echo "::set-output name=kubeconfig::$(oc config view --flatten=true --minify=true)"
          echo "we did it"

  openshift-readconfig:
    name: OpenShift Load Config
    runs-on: ubuntu-latest

    needs: openshift-auth

    steps:
      - name: Load Config
        env:
          KUBECONFIG: kubeconfig.yaml
        run: |
          echo "The kube config file is $KUBECONFIG"
          echo "${{ needs.auth.outputs.kubeconfig }}" | tee $KUBECONFIG
          cat $KUBECONFIG
          echo "okay"
