name: Link checker
on:
  push:
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  markdown-link-check:
    name: Check links in markdown
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - name: Check links
        uses: lycheeverse/lychee-action@v2
        with:
          args: '--verbose --no-progress **/*.md'
